CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(254) NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    display_name         VARCHAR(80)  NOT NULL,
    wardrobe_type        VARCHAR(16),
    style_preferences    VARCHAR(200) NOT NULL DEFAULT '',
    onboarding_completed BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX ux_users_email ON users (email);

CREATE TABLE images (
    id                   UUID PRIMARY KEY,
    owner_id             BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    original_file        VARCHAR(120) NOT NULL,
    display_file         VARCHAR(120) NOT NULL,
    thumb_file           VARCHAR(120) NOT NULL,
    width                INTEGER      NOT NULL,
    height               INTEGER      NOT NULL,
    detected_color       VARCHAR(16),
    detected_hex         VARCHAR(7),
    detection_confidence DOUBLE PRECISION,
    pattern_likely       BOOLEAN      NOT NULL DEFAULT FALSE,
    attached             BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_images_owner ON images (owner_id);
CREATE INDEX ix_images_drafts ON images (attached, created_at);

CREATE TABLE garments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    image_id     UUID        NOT NULL REFERENCES images (id) ON DELETE CASCADE,
    name         VARCHAR(80),
    category     VARCHAR(16) NOT NULL,
    subcategory  VARCHAR(24) NOT NULL,
    color        VARCHAR(16) NOT NULL,
    color_hex    VARCHAR(7)  NOT NULL,
    color_source VARCHAR(8)  NOT NULL,
    pattern      BOOLEAN     NOT NULL DEFAULT FALSE,
    seasons      VARCHAR(64) NOT NULL,
    occasions    VARCHAR(64) NOT NULL,
    favorite     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_garments_owner ON garments (owner_id);
CREATE UNIQUE INDEX ux_garments_image ON garments (image_id);

CREATE TABLE saved_outfits (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    outfit_key VARCHAR(200) NOT NULL,
    title      VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX ux_saved_outfits_owner_key ON saved_outfits (owner_id, outfit_key);
