-- Firebase sign-in (Apple / Google / e-mail), roles and account state
ALTER TABLE users ADD COLUMN firebase_uid VARCHAR(128);
ALTER TABLE users ADD COLUMN auth_provider VARCHAR(16) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN role VARCHAR(16) NOT NULL DEFAULT 'USER';
ALTER TABLE users ADD COLUMN disabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
CREATE UNIQUE INDEX ux_users_firebase_uid ON users (firebase_uid);

-- Settings managed in the admin panel (links, providers, Firebase web config, maintenance, ...)
CREATE TABLE app_settings (
    setting_key VARCHAR(80) PRIMARY KEY,
    setting_value VARCHAR(4000),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by  BIGINT
);

-- Curated color palettes used by the outfit engine (seeded from palettes.json, editable in the admin panel)
CREATE TABLE palettes (
    id         VARCHAR(16) PRIMARY KEY,
    colors     VARCHAR(200)  NOT NULL,
    names      VARCHAR(4000) NOT NULL DEFAULT '{}',
    enabled    BOOLEAN       NOT NULL DEFAULT TRUE,
    built_in   BOOLEAN       NOT NULL DEFAULT FALSE,
    sort_order INTEGER       NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Deletion requests from people who cannot sign in (reviewed in the admin panel)
CREATE TABLE deletion_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference       VARCHAR(16)  NOT NULL,
    email           VARCHAR(254) NOT NULL,
    message         VARCHAR(1000),
    language        VARCHAR(8),
    status          VARCHAR(16)  NOT NULL,
    note            VARCHAR(1000),
    resolved_by     BIGINT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at     TIMESTAMP WITH TIME ZONE
);
CREATE UNIQUE INDEX ux_deletion_requests_reference ON deletion_requests (reference);
CREATE INDEX ix_deletion_requests_status ON deletion_requests (status, created_at);

-- Anonymized record of completed deletions (no personal data: e-mail is a salted hash)
CREATE TABLE deletion_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_hash    VARCHAR(64)  NOT NULL,
    auth_provider VARCHAR(16)  NOT NULL,
    method        VARCHAR(16)  NOT NULL,
    reason        VARCHAR(1000),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
